# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  travelcapstone.backend.api:
    build:
      context: "D:\\workspace\\github\\TravelCapstone.BackEnd"
      dockerfile: "TravelCapstone.BackEnd.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/TravelCapstone.BackEnd.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "travelcapstonebackendapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\duong\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\workspace\\github\\TravelCapstone.BackEnd\\TravelCapstone.BackEnd.API:/app:rw"
    - "D:\\workspace\\github\\TravelCapstone.BackEnd:/src:rw"
    working_dir: "/app"
