name: Build and deploy container app to Azure Web App - coc-travel

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: https://coctravel.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a0fd248557944359a5080c4146f75006 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_35c2fd8d04044fa1b6bd502d1100d4a6 }}

    - name: Build and push container image to Azure Container Registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: coctravel.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a0fd248557944359a5080c4146f75006 }}/travelcapstonebackendapi:${{ github.sha }}
        file: ./Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DockerHub_Username }}
        password: ${{ secrets.DockerHub_Password }}

    - name: Build and push container image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: hongquan0312/coc-travel:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'coc-travel'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1b997ea7b78944499665df076fac5fd7 }}
        images: 'coctravel.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a0fd248557944359a5080c4146f75006 }}/travelcapstonebackendapi:${{ github.sha }}'
